[package]
name = "ctrl"
version = "0.1.0"
authors = ["Robin Ole Heinemann <robin.ole.heinemann@t-online.de>"]

[dependencies]
fuseable = { path = "fuseable" }
fuseable_derive = { path = "fuseable_derive" }
fuse_mt = "*"
serde = { version = "*", features = ["rc"] }
# serde_state = { version = "*", path = "serde_state/serde_state" }
serde_derive = "*"
serde_derive_state = { version = "*", path = "serde_state/serde_derive" }
serde_yaml = { version = "*", path = "serde_yaml" }
num = "*"
itertools = "*"
structopt = "*"
lazy_static = "*"
i2c-linux = "*"
isomorphism = { version = "*", features = ["serde"] }

[profile.release]
lto = true
codegen-units = 16
panic = 'abort'
