[package]
name = "fuseable_derive"
version = "0.1.0"
authors = ["Robin Ole Heinemann <robin.ole.heinemann@t-online.de>"]

[dependencies]
syn = { version = ">= 0.15.4", features = ["extra-traits"]}
quote = "*"
proc-macro2 = "*"

[lib]
name = "fuseable_derive"
proc-macro = true
